/* tslint:disable */
/* eslint-disable */
/**
 * Authentication API
 * Husqvarna Group Authentication API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostOAuth2Response
 */
export interface PostOAuth2Response {
    /**
     * Access token (JWT) with information about the current logged in user.
     * @type {string}
     * @memberof PostOAuth2Response
     */
    'access_token'?: string;
    /**
     * Scope
     * @type {string}
     * @memberof PostOAuth2Response
     */
    'scope'?: string;
    /**
     * Timestamp expires in seconds
     * @type {number}
     * @memberof PostOAuth2Response
     */
    'expires_in'?: number;
    /**
     * Refresh token
     * @type {string}
     * @memberof PostOAuth2Response
     */
    'refresh_token'?: string;
    /**
     * Token provider
     * @type {string}
     * @memberof PostOAuth2Response
     */
    'provider'?: string;
    /**
     * User id
     * @type {string}
     * @memberof PostOAuth2Response
     */
    'user_id'?: string;
    /**
     * Bearer
     * @type {string}
     * @memberof PostOAuth2Response
     */
    'token_type'?: string;
}

