/* tslint:disable */
/* eslint-disable */
/**
 * Authentication API
 * Husqvarna Group Authentication API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/oauth2-api';

