/* tslint:disable */
/* eslint-disable */
/**
 * Husqvarna Connectivity API
 * This API allows you to obtain information about your Husqvarna connected products.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeviceAttributesAnyOf } from './device-attributes-any-of';
// May contain unused imports in some cases
// @ts-ignore
import type { DeviceAttributesAnyOf1 } from './device-attributes-any-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { DeviceAttributesAnyOf2 } from './device-attributes-any-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { DeviceAttributesAnyOf3 } from './device-attributes-any-of3';
// May contain unused imports in some cases
// @ts-ignore
import type { DeviceResponseDataAttributesUdm } from './device-response-data-attributes-udm';

/**
 * 
 * @export
 * @interface DeviceAttributes
 */
export interface DeviceAttributes {
    /**
     * 
     * @type {DeviceResponseDataAttributesUdm}
     * @memberof DeviceAttributes
     */
    'happ'?: DeviceResponseDataAttributesUdm;
    /**
     * 
     * @type {DeviceResponseDataAttributesUdm}
     * @memberof DeviceAttributes
     */
    'ble-advertise'?: DeviceResponseDataAttributesUdm;
    /**
     * 
     * @type {DeviceResponseDataAttributesUdm}
     * @memberof DeviceAttributes
     */
    'trackunit'?: DeviceResponseDataAttributesUdm;
    /**
     * 
     * @type {DeviceResponseDataAttributesUdm}
     * @memberof DeviceAttributes
     */
    'mower'?: DeviceResponseDataAttributesUdm;
}

