/* tslint:disable */
/* eslint-disable */
/**
 * Husqvarna Connectivity API
 * This API allows you to obtain information about your Husqvarna connected products.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeviceAttributes } from './device-attributes';

/**
 * 
 * @export
 * @interface FullDeviceResponseData
 */
export interface FullDeviceResponseData {
    /**
     * 
     * @type {string}
     * @memberof FullDeviceResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof FullDeviceResponseData
     */
    'type'?: string;
    /**
     * 
     * @type {DeviceAttributes}
     * @memberof FullDeviceResponseData
     */
    'attributes'?: DeviceAttributes;
}

