/* tslint:disable */
/* eslint-disable */
/**
 * Husqvarna Connectivity API
 * This API allows you to obtain information about your Husqvarna connected products.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A {JSON:API} error message.
 * @export
 * @interface JsonApiErrorObject
 */
export interface JsonApiErrorObject {
    /**
     * 
     * @type {string}
     * @memberof JsonApiErrorObject
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof JsonApiErrorObject
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof JsonApiErrorObject
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof JsonApiErrorObject
     */
    'detail'?: string;
}

