/* tslint:disable */
/* eslint-disable */
/**
 * Husqvarna Connectivity API
 * This API allows you to obtain information about your Husqvarna connected products.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SpecificationResponseData
 */
export interface SpecificationResponseData {
    /**
     * 
     * @type {string}
     * @memberof SpecificationResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpecificationResponseData
     */
    'type'?: string;
    /**
     * 
     * @type {object}
     * @memberof SpecificationResponseData
     */
    'attributes'?: object;
}

