/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information about the battery in the Automower®
 * @export
 * @interface Battery
 */
export interface Battery {
    /**
     * The current battery level percentage
     * @type {number}
     * @memberof Battery
     */
    'batteryPercent': number;
}

