/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CalendarTask } from './calendar-task';

/**
 * Information about the calendar tasks. An Automower® can have several tasks. If the mower supports work areas the property workAreaId is required to connect the task to an work area.
 * @export
 * @interface Calendar
 */
export interface Calendar {
    /**
     * 
     * @type {Array<CalendarTask>}
     * @memberof Calendar
     */
    'tasks'?: Array<CalendarTask>;
}

