/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CalendarTask
 */
export interface CalendarTask {
    /**
     * Start time expressed in minutes after midnight.
     * @type {number}
     * @memberof CalendarTask
     */
    'start': number;
    /**
     * Duration time expressed in minutes.
     * @type {number}
     * @memberof CalendarTask
     */
    'duration': number;
    /**
     * Enabled on Mondays
     * @type {boolean}
     * @memberof CalendarTask
     */
    'monday': boolean;
    /**
     * Enabled on Tuesdays
     * @type {boolean}
     * @memberof CalendarTask
     */
    'tuesday': boolean;
    /**
     * Enabled on Wednesdays
     * @type {boolean}
     * @memberof CalendarTask
     */
    'wednesday': boolean;
    /**
     * Enabled on Thursdays
     * @type {boolean}
     * @memberof CalendarTask
     */
    'thursday': boolean;
    /**
     * Enabled on Fridays
     * @type {boolean}
     * @memberof CalendarTask
     */
    'friday': boolean;
    /**
     * Enabled on Saturdays
     * @type {boolean}
     * @memberof CalendarTask
     */
    'saturday': boolean;
    /**
     * Enabled on Sundays
     * @type {boolean}
     * @memberof CalendarTask
     */
    'sunday': boolean;
}

