/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information about what capabilities the Automower® has
 * @export
 * @interface Capabilities
 */
export interface Capabilities {
    /**
     * If the Automower® supports the command confirm error. The error also needs to be confirmable.
     * @type {boolean}
     * @memberof Capabilities
     */
    'canConfirmError': boolean;
    /**
     * If the Automower® supports headlights
     * @type {boolean}
     * @memberof Capabilities
     */
    'headlights': boolean;
    /**
     * If the Automower® supports GPS position. If false no positions are available.
     * @type {boolean}
     * @memberof Capabilities
     */
    'position': boolean;
    /**
     * If the Automower® supports stay-out zones
     * @type {boolean}
     * @memberof Capabilities
     */
    'stayOutZones': boolean;
    /**
     * If the Automower® supports work areas
     * @type {boolean}
     * @memberof Capabilities
     */
    'workAreas': boolean;
}

