/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information about headlights. Not all Automower® models supports headlight and not all enums are available for all models.
 * @export
 * @interface HeadlightHeadlight
 */
export interface HeadlightHeadlight {
    /**
     * Mode:   * `ALWAYS_ON` - Always on.   * `ALWAYS_OFF` - Always off.   * `EVENING_ONLY` - Only in the evening.   * `EVENING_AND_NIGHT` - In evening and night. 
     * @type {string}
     * @memberof HeadlightHeadlight
     */
    'mode': HeadlightHeadlightModeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum HeadlightHeadlightModeEnum {
    ALWAYS_ON = 'ALWAYS_ON',
    ALWAYS_OFF = 'ALWAYS_OFF',
    EVENING_ONLY = 'EVENING_ONLY',
    EVENING_AND_NIGHT = 'EVENING_AND_NIGHT'
}


