/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkAreaData } from './work-area-data';

/**
 * A primary data object compliant with the JSON API Specification.
 * @export
 * @interface JsonApiDataWorkArea
 */
export interface JsonApiDataWorkArea {
    /**
     * The type of the data object.
     * @type {string}
     * @memberof JsonApiDataWorkArea
     */
    'type'?: string;
    /**
     * The identity of the work area
     * @type {number}
     * @memberof JsonApiDataWorkArea
     */
    'id'?: number;
    /**
     * 
     * @type {WorkAreaData}
     * @memberof JsonApiDataWorkArea
     */
    'attributes'?: WorkAreaData;
}

