/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JsonApiDataWorkArea } from './json-api-data-work-area';

/**
 * A data document compliant with the JSON API Specification.
 * @export
 * @interface JsonApiDataDocumentWorkArea
 */
export interface JsonApiDataDocumentWorkArea {
    /**
     * 
     * @type {JsonApiDataWorkArea}
     * @memberof JsonApiDataDocumentWorkArea
     */
    'data'?: JsonApiDataWorkArea;
}

