/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MowerData } from './mower-data';

/**
 * A primary data object compliant with the JSON API Specification.
 * @export
 * @interface JsonApiData
 */
export interface JsonApiData {
    /**
     * The type of the data object.
     * @type {string}
     * @memberof JsonApiData
     */
    'type'?: string;
    /**
     * The identity of the data object
     * @type {string}
     * @memberof JsonApiData
     */
    'id'?: string;
    /**
     * 
     * @type {MowerData}
     * @memberof JsonApiData
     */
    'attributes'?: MowerData;
}

