/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A primary error object compliant with the JSON API Specification.
 * @export
 * @interface JsonApiError
 */
export interface JsonApiError {
    /**
     * A unique identifier for this particular occurrence of the problem.
     * @type {string}
     * @memberof JsonApiError
     */
    'id'?: string;
    /**
     * The HTTP status code applicable to this problem, expressed as a string value.
     * @type {string}
     * @memberof JsonApiError
     */
    'status'?: string;
    /**
     * An application specific error code, expressed as a string value.
     * @type {string}
     * @memberof JsonApiError
     */
    'code'?: string;
    /**
     * A short, human readable summary of the problem that should not change from occurrence to occurrence of the problem, except for purposes of localization.
     * @type {string}
     * @memberof JsonApiError
     */
    'title'?: string;
    /**
     * A human readable explanation specific to this occurrence of the problem. Like title, this value can be localized.
     * @type {string}
     * @memberof JsonApiError
     */
    'detail'?: string;
}

