/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Message } from './message';

/**
 * A list of messages if supported by the Automower®. Messages are generated by the Automower® with different severity. 
 * @export
 * @interface Messages
 */
export interface Messages {
    /**
     * List of all messages for the Automower®.
     * @type {Array<Message>}
     * @memberof Messages
     */
    'messages'?: Array<Message>;
}

