/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An error message with information when and where it occurred. Every message has a severity how much the error affect the Automower®.
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * Timestamp for the message in milliseconds since 1970-01-01T00:00:00 in local time. NOTE! This timestamp is in local time for the mower and is coming directly from the Automower®.
     * @type {number}
     * @memberof Message
     */
    'time': number;
    /**
     * The error code. Please see https://developer.husqvarnagroup.cloud/apis/automower-connect-api?tab=status%20description%20and%20error%20codes for details
     * @type {number}
     * @memberof Message
     */
    'code': number;
    /**
     * The severity of the error message.
     * @type {string}
     * @memberof Message
     */
    'severity': MessageSeverityEnum;
    /**
     * Only available if the message has a position.
     * @type {number}
     * @memberof Message
     */
    'latitude'?: number;
    /**
     * Only available if the message has a position.
     * @type {number}
     * @memberof Message
     */
    'longitude'?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum MessageSeverityEnum {
    FATAL = 'FATAL',
    ERROR = 'ERROR',
    WARNING = 'WARNING',
    INFO = 'INFO',
    DEBUG = 'DEBUG',
    SW = 'SW',
    UNKNOWN = 'UNKNOWN'
}


