/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information if the mower is connected to the cloud and when last status was reported by the mower to the cloud.
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * Is the mower currently connected to the cloud. The mower needs to be connected to send command to the mower.
     * @type {boolean}
     * @memberof Metadata
     */
    'connected': boolean;
    /**
     * Timestamp for the last status update in milliseconds since 1970-01-01T00:00:00 in UTC time. NOTE! This timestamp is generated in the backend and not from the Mower.
     * @type {number}
     * @memberof Metadata
     */
    'statusTimestamp': number;
}

