/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MowersIdWorkAreasWorkAreaIdPatchRequestDataAttributes } from './mowers-id-work-areas-work-area-id-patch-request-data-attributes';

/**
 * 
 * @export
 * @interface MowersIdWorkAreasWorkAreaIdPatchRequestData
 */
export interface MowersIdWorkAreasWorkAreaIdPatchRequestData {
    /**
     * 
     * @type {number}
     * @memberof MowersIdWorkAreasWorkAreaIdPatchRequestData
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof MowersIdWorkAreasWorkAreaIdPatchRequestData
     */
    'type': MowersIdWorkAreasWorkAreaIdPatchRequestDataTypeEnum;
    /**
     * 
     * @type {MowersIdWorkAreasWorkAreaIdPatchRequestDataAttributes}
     * @memberof MowersIdWorkAreasWorkAreaIdPatchRequestData
     */
    'attributes': MowersIdWorkAreasWorkAreaIdPatchRequestDataAttributes;
}

/**
    * @export
    * @enum {string}
    */
export enum MowersIdWorkAreasWorkAreaIdPatchRequestDataTypeEnum {
    WORK_AREA = 'workArea'
}


