/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information about the mowers current status
 * @export
 * @interface MowerApp
 */
export interface MowerApp {
    /**
     * Mode:   * `MAIN_AREA` - Mower will mow until low battery. Go home and charge. Leave and continue mowing.   * `SECONDARY_AREA` - Mower will mow until empty battery, or a limited time. When done, it stops in the garden.   * `HOME` - Mower goes home and parks forever.   * `DEMO` - Same as main area, but shorter times. (No blade operation)   * `UNKNOWN` - Unknown mode.   * `POI` - Point of interest. 
     * @type {string}
     * @memberof MowerApp
     */
    'mode': MowerAppModeEnum;
    /**
     * Activity:   * `UNKNOWN` - Unknown.   * `NOT_APPLICABLE` - Not applicable.   * `MOWING` - Mower is currently mowing.   * `GOING_HOME` - Mower is currently going home to the charging station.   * `CHARGING` - Mower is currently charging. Note that the mower will only report the activity charging if it was its own decision to go home and charge. I.e., it would like to mow but is charging because it has to. If the mower is restricted it may very well charge when in the charging station, but the activity will be Parked.   * `LEAVING` - Mower is currently leaving the charging station and is heading out to a starting point.   * `PARKED_IN_CS` - Mower is parked in the charging station.   * `STOPPED_IN_GARDEN` - Mower has stopped in garden, for instance in manual mode when the task has been completed. 
     * @type {string}
     * @memberof MowerApp
     */
    'activity': MowerAppActivityEnum;
    /**
     * Inactive reason:   * `NONE` - No inactive reason.   * `PLANNING` - The mower is planning a path or a work area.   * `SEARCHING_FOR_SATELLITES` - Waiting for fix when using EPOS. 
     * @type {string}
     * @memberof MowerApp
     */
    'inactiveReason'?: MowerAppInactiveReasonEnum;
    /**
     * State:   * `UNKNOWN` - Unknown.   * `PAUSED` - Not applicable.   * `IN_OPERATION` - Mower is operating according to selected mode. The activity gives information about what it is currently up to.   * `WAIT_UPDATING` - Mower is in wait state when updating.   * `WAIT_POWER_UP` - Mower is in wait state when powering up.   * `RESTRICTED` - The mower is currently restricted from mowing for some reason. It will continue mowing when the restriction is removed. The activity gives information about what the mower is currently up to.   * `OFF` - Mower is turned off   * `STOPPED` - Mower is stopped, and cannot be started remotely. Start requirements (safety or other) are not fulfilled.   * `ERROR` - A temporary error has occurred. If the error is resolved, the mower will resume operation without user interaction. Typically, this happens when the loop signal is lost. When it comes back, the operation is resumed.   * `FATAL_ERROR` - A fatal error has occurred. Error has to be fixed confirmed to leave this state.   * `ERROR_AT_POWER_UP` - An error at power up. 
     * @type {string}
     * @memberof MowerApp
     */
    'state': MowerAppStateEnum;
    /**
     * Current work area id. If the mower supports work areas and the mower is working on a work area. If no current work area is selected this attribute is not set.
     * @type {number}
     * @memberof MowerApp
     */
    'workAreaId'?: number;
    /**
     * 
     * @type {number}
     * @memberof MowerApp
     */
    'errorCode'?: number;
    /**
     * Timestamp for the last error code in milliseconds since 1970-01-01T00:00:00 in local time. NOTE! This timestamp is in local time for the mower and is coming directly from the mower.
     * @type {number}
     * @memberof MowerApp
     */
    'errorCodeTimestamp'?: number;
    /**
     * If the mower has an errorCode this attribute state if the error is confirmable. If true the POST `/mowers/{id}/errors/confirm` will be successful. 
     * @type {boolean}
     * @memberof MowerApp
     */
    'isErrorConfirmable'?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum MowerAppModeEnum {
    MAIN_AREA = 'MAIN_AREA',
    SECONDARY_AREA = 'SECONDARY_AREA',
    HOME = 'HOME',
    DEMO = 'DEMO',
    UNKNOWN = 'UNKNOWN',
    POI = 'POI'
}
/**
    * @export
    * @enum {string}
    */
export enum MowerAppActivityEnum {
    UNKNOWN = 'UNKNOWN',
    NOT_APPLICABLE = 'NOT_APPLICABLE',
    MOWING = 'MOWING',
    GOING_HOME = 'GOING_HOME',
    CHARGING = 'CHARGING',
    LEAVING = 'LEAVING',
    PARKED_IN_CS = 'PARKED_IN_CS',
    STOPPED_IN_GARDEN = 'STOPPED_IN_GARDEN'
}
/**
    * @export
    * @enum {string}
    */
export enum MowerAppInactiveReasonEnum {
    NONE = 'NONE',
    PLANNING = 'PLANNING',
    SEARCHING_FOR_SATELLITES = 'SEARCHING_FOR_SATELLITES'
}
/**
    * @export
    * @enum {string}
    */
export enum MowerAppStateEnum {
    UNKNOWN = 'UNKNOWN',
    PAUSED = 'PAUSED',
    IN_OPERATION = 'IN_OPERATION',
    WAIT_UPDATING = 'WAIT_UPDATING',
    WAIT_POWER_UP = 'WAIT_POWER_UP',
    RESTRICTED = 'RESTRICTED',
    OFF = 'OFF',
    STOPPED = 'STOPPED',
    ERROR = 'ERROR',
    FATAL_ERROR = 'FATAL_ERROR',
    ERROR_AT_POWER_UP = 'ERROR_AT_POWER_UP'
}


