/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DurationAttributes } from './duration-attributes';
// May contain unused imports in some cases
// @ts-ignore
import type { Park } from './park';
// May contain unused imports in some cases
// @ts-ignore
import type { ParkUntilFurtherNotice } from './park-until-further-notice';
// May contain unused imports in some cases
// @ts-ignore
import type { ParkUntilNextSchedule } from './park-until-next-schedule';
// May contain unused imports in some cases
// @ts-ignore
import type { Pause } from './pause';
// May contain unused imports in some cases
// @ts-ignore
import type { ResumeSchedule } from './resume-schedule';
// May contain unused imports in some cases
// @ts-ignore
import type { Start } from './start';
// May contain unused imports in some cases
// @ts-ignore
import type { StartInWorkArea } from './start-in-work-area';

/**
 * @type MowersIdActionsPostRequestData
 * @export
 */
export type MowersIdActionsPostRequestData = Park | ParkUntilFurtherNotice | ParkUntilNextSchedule | Pause | ResumeSchedule | Start | StartInWorkArea;


