/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Battery } from './battery';
// May contain unused imports in some cases
// @ts-ignore
import type { Calendar } from './calendar';
// May contain unused imports in some cases
// @ts-ignore
import type { Capabilities } from './capabilities';
// May contain unused imports in some cases
// @ts-ignore
import type { Metadata } from './metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { MowerApp } from './mower-app';
// May contain unused imports in some cases
// @ts-ignore
import type { Planner } from './planner';
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';
// May contain unused imports in some cases
// @ts-ignore
import type { Settings } from './settings';
// May contain unused imports in some cases
// @ts-ignore
import type { Statistics } from './statistics';
// May contain unused imports in some cases
// @ts-ignore
import type { StayOutZones } from './stay-out-zones';
// May contain unused imports in some cases
// @ts-ignore
import type { System } from './system';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkArea } from './work-area';

/**
 * A mower data object with all data for a mower.
 * @export
 * @interface MowerData
 */
export interface MowerData {
    /**
     * 
     * @type {System}
     * @memberof MowerData
     */
    'system': System;
    /**
     * 
     * @type {Battery}
     * @memberof MowerData
     */
    'battery': Battery;
    /**
     * 
     * @type {Capabilities}
     * @memberof MowerData
     */
    'capabilities'?: Capabilities;
    /**
     * 
     * @type {MowerApp}
     * @memberof MowerData
     */
    'mower': MowerApp;
    /**
     * 
     * @type {Calendar}
     * @memberof MowerData
     */
    'calendar'?: Calendar;
    /**
     * 
     * @type {Planner}
     * @memberof MowerData
     */
    'planner': Planner;
    /**
     * 
     * @type {Metadata}
     * @memberof MowerData
     */
    'metadata': Metadata;
    /**
     * List of the GPS positions. Latest registered position is first in the array and the oldest last in the array. Max number of positions is 50 after that the latest position is removed from the array.
     * @type {Array<Position>}
     * @memberof MowerData
     */
    'positions'?: Array<Position>;
    /**
     * 
     * @type {Settings}
     * @memberof MowerData
     */
    'settings'?: Settings;
    /**
     * 
     * @type {Statistics}
     * @memberof MowerData
     */
    'statistics'?: Statistics;
    /**
     * 
     * @type {StayOutZones}
     * @memberof MowerData
     */
    'stayOutZones'?: StayOutZones;
    /**
     * List of all work areas if supported by the Automower®. If empty list, no work areas are created. By default there should be a default work area with id 0.
     * @type {Array<WorkArea>}
     * @memberof MowerData
     */
    'workAreas'?: Array<WorkArea>;
}

