/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CuttingHeight } from './cutting-height';
// May contain unused imports in some cases
// @ts-ignore
import type { Headlight } from './headlight';
// May contain unused imports in some cases
// @ts-ignore
import type { HeadlightHeadlight } from './headlight-headlight';
// May contain unused imports in some cases
// @ts-ignore
import type { Timer } from './timer';

/**
 * 
 * @export
 * @interface MowersIdSettingsPostRequestDataAttributes
 */
export interface MowersIdSettingsPostRequestDataAttributes {
    /**
     * Selected cutting height, Range:1-9
     * @type {number}
     * @memberof MowersIdSettingsPostRequestDataAttributes
     */
    'cuttingHeight'?: number;
    /**
     * Timestamp in seconds from 1970-01-01. The timestamp needs to be in 24 hours from UTC time.
     * @type {number}
     * @memberof MowersIdSettingsPostRequestDataAttributes
     */
    'dateTime'?: number;
    /**
     * Time zone needed for mowers that don\'t support work areas. The time zone can be a time zone or GMT +- offset i.e. GMT+2. It\'s recommended to use a time zone to auto adjust for daylight saving time (DST).
     * @type {string}
     * @memberof MowersIdSettingsPostRequestDataAttributes
     */
    'timeZone'?: string;
    /**
     * 
     * @type {HeadlightHeadlight}
     * @memberof MowersIdSettingsPostRequestDataAttributes
     */
    'headlight'?: HeadlightHeadlight;
}

