/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MowersIdWorkAreasWorkAreaIdPatchRequestDataAttributes
 */
export interface MowersIdWorkAreasWorkAreaIdPatchRequestDataAttributes {
    /**
     * 
     * @type {number}
     * @memberof MowersIdWorkAreasWorkAreaIdPatchRequestDataAttributes
     */
    'cuttingHeight'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MowersIdWorkAreasWorkAreaIdPatchRequestDataAttributes
     */
    'enable'?: boolean;
}

