/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MowersIdStayOutZonesStayOutIdPatchRequestDataAttributes } from './mowers-id-stay-out-zones-stay-out-id-patch-request-data-attributes';

/**
 * 
 * @export
 * @interface MowersIdStayOutZonesStayOutIdPatchRequestData
 */
export interface MowersIdStayOutZonesStayOutIdPatchRequestData {
    /**
     * 
     * @type {string}
     * @memberof MowersIdStayOutZonesStayOutIdPatchRequestData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MowersIdStayOutZonesStayOutIdPatchRequestData
     */
    'type': MowersIdStayOutZonesStayOutIdPatchRequestDataTypeEnum;
    /**
     * 
     * @type {MowersIdStayOutZonesStayOutIdPatchRequestDataAttributes}
     * @memberof MowersIdStayOutZonesStayOutIdPatchRequestData
     */
    'attributes': MowersIdStayOutZonesStayOutIdPatchRequestDataAttributes;
}

/**
    * @export
    * @enum {string}
    */
export enum MowersIdStayOutZonesStayOutIdPatchRequestDataTypeEnum {
    STAY_OUT_ZONE = 'stayOutZone'
}


