/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PlannerOverride } from './planner-override';

/**
 * Information about the planner. The planner tells when the mower should work.
 * @export
 * @interface Planner
 */
export interface Planner {
    /**
     * Timestamp for the next auto start in milliseconds since 1970-01-01T00:00:00 in local time.  If the mower is charging then the value is the estimated time when it will be leaving the charging station.  If the value is 0 then the mower should start now.  NOTE! This timestamp is in local time for the mower and is coming directly from the mower.
     * @type {number}
     * @memberof Planner
     */
    'nextStartTimestamp': number;
    /**
     * 
     * @type {PlannerOverride}
     * @memberof Planner
     */
    'override'?: PlannerOverride;
    /**
     * Restricted reason:   * `NONE` - No restricted reason.   * `WEEK_SCHEDULE` - There is no task in the Calendar right now, nothing to do.   * `PARK_OVERRIDE` - The restriction is because someone forced us to park, using the override feature.   * `SENSOR` - The sensor has decided that the grass is short enough, so there is no need to wear it down even more.   * `DAILY_LIMIT` - If a model has a maximum allowed mowing time per day, this restriction will apply when that time has run out.   * `FOTA` - When a Fota update is being transferred to the mower, we want to remain in the charging station to ensure that the transfer is successful. The restriction is removed when the transfer is done.   * `FROST` - The frost sensor thinks it is too cold to mow.   * `ALL_WORK_AREAS_COMPLETED` - All work areas are completed.   * `EXTERNAL` - An external reason set by an external tool. Can be IFTTT, Google Assistant or Amazon Alexa. See externalReason for more information 
     * @type {string}
     * @memberof Planner
     */
    'restrictedReason': PlannerRestrictedReasonEnum;
    /**
     * External reason set by i.e. IFTTT, Google Assistant or Amazon Alexa. Ranges:   * `1000 - 1999` - Google Assistant.   * `2000 - 2999` - Amazon Alexa.   * `3000 - 3999` - Home Assistant.   * `4000` - IFTTT, Wildlife consideration.   * `4001` - IFTTT, Frost & rain guard.   * `4002` - IFTTT, Calendar connection.   * `4000 - 4999` - IFTTT.   * `5000 - 5999` - GARDENA Smart System.   * `6000` - Smart routine Rain guard   * `6001` - Smart routine Frost guard.   * `6500` - Smart routine Wildlife protection.   * `6000 - 6999` - Smart routine.   * `100 000 - 199 999` - IFTTT applets.   * `200 000 - 299 999` - Developer Portal. 
     * @type {number}
     * @memberof Planner
     */
    'externalReason'?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum PlannerRestrictedReasonEnum {
    NONE = 'NONE',
    WEEK_SCHEDULE = 'WEEK_SCHEDULE',
    PARK_OVERRIDE = 'PARK_OVERRIDE',
    SENSOR = 'SENSOR',
    DAILY_LIMIT = 'DAILY_LIMIT',
    FOTA = 'FOTA',
    FROST = 'FROST',
    ALL_WORK_AREAS_COMPLETED = 'ALL_WORK_AREAS_COMPLETED',
    EXTERNAL = 'EXTERNAL'
}


