/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The Planner has an override feature, which can be used to override the operation decided by the Calendar. There is room for one override at a time, and it occurs from now and for a duration of time.
 * @export
 * @interface PlannerOverride
 */
export interface PlannerOverride {
    /**
     * Action:   * `NOT_ACTIVE` - Not active.   * `FORCE_PARK` - Force park until next start means that no more mowing will be done within the current task. Operation will be resumed at the start of the next task instead.   * `FORCE_MOW` - Force the mower to mow for the specified amount of time. When the time has elapsed, the override is removed and the Planner reverts to the Calendar instead. 
     * @type {string}
     * @memberof PlannerOverride
     */
    'action': PlannerOverrideActionEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum PlannerOverrideActionEnum {
    NOT_ACTIVE = 'NOT_ACTIVE',
    FORCE_PARK = 'FORCE_PARK',
    FORCE_MOW = 'FORCE_MOW'
}


