/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JsonApiAction } from './json-api-action';

/**
 * @type ResumeSchedule
 * Removes any override on the Planner and let the mower resume to the schedule set by the Calendar
 * @export
 */
export type ResumeSchedule = JsonApiAction;


