/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CuttingHeight } from './cutting-height';
// May contain unused imports in some cases
// @ts-ignore
import type { Headlight } from './headlight';
// May contain unused imports in some cases
// @ts-ignore
import type { HeadlightHeadlight } from './headlight-headlight';
// May contain unused imports in some cases
// @ts-ignore
import type { Timer } from './timer';

/**
 * @type Settings
 * Information about the settings
 * @export
 */
export type Settings = CuttingHeight & Headlight & Timer;


