/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information about the statistics. If a value is missing the mower does not support the value.
 * @export
 * @interface Statistics
 */
export interface Statistics {
    /**
     * The number of seconds since the last reset of the cutting blade usage counter.
     * @type {number}
     * @memberof Statistics
     */
    'cuttingBladeUsageTime'?: number;
    /**
     * The number of seconds the mower has been disconnected from the cloud. Not available on all models.
     * @type {number}
     * @memberof Statistics
     */
    'downTime'?: number;
    /**
     * Number of charging cycles.
     * @type {number}
     * @memberof Statistics
     */
    'numberOfChargingCycles'?: number;
    /**
     * The total number of collisions.
     * @type {number}
     * @memberof Statistics
     */
    'numberOfCollisions'?: number;
    /**
     * Total charging time in seconds.
     * @type {number}
     * @memberof Statistics
     */
    'totalChargingTime'?: number;
    /**
     * Total cutting time in seconds.
     * @type {number}
     * @memberof Statistics
     */
    'totalCuttingTime'?: number;
    /**
     * Total drive distance in meters. It\'s a calculated value based on totalRunningTime multiply with average speed for the mower depending on the model.
     * @type {number}
     * @memberof Statistics
     */
    'totalDriveDistance'?: number;
    /**
     * The total running time in seconds. (the wheel motors have been running)
     * @type {number}
     * @memberof Statistics
     */
    'totalRunningTime'?: number;
    /**
     * The total searching time in seconds.
     * @type {number}
     * @memberof Statistics
     */
    'totalSearchingTime'?: number;
    /**
     * The number of seconds the mower has been connected to the cloud.
     * @type {number}
     * @memberof Statistics
     */
    'upTime'?: number;
}

