/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A stay-out zone is an area that you can use to protect an area on you lawn. The Automower® will not access the are when the zone is enabled.
 * @export
 * @interface StayOutZone
 */
export interface StayOutZone {
    /**
     * 
     * @type {string}
     * @memberof StayOutZone
     */
    'id'?: string;
    /**
     * Name of stay-out zone
     * @type {string}
     * @memberof StayOutZone
     */
    'name'?: string;
    /**
     * If the stay-out zone is enabled, the Automower® will not access the zone.
     * @type {boolean}
     * @memberof StayOutZone
     */
    'enabled'?: boolean;
}

