/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StayOutZone } from './stay-out-zone';

/**
 * Information about stay-out zones if supported by the Automower®. Stay-out zones are managed in the Automower® Connect app. To create a stay-out zone you need to use the Automower® Connect app.   You can create stay-out zones around areas of your lawn that you do not want the mower to enter: for example, if you have an area with newly sown grass or beautiful spring flowers. The stay-out zone can be activated or deactivated, but not scheduled. 
 * @export
 * @interface StayOutZones
 */
export interface StayOutZones {
    /**
     * If the stay-out zones are synchronized with the Husqvarna cloud. If the map is dirty you can not enable or disable a stay-out zone.
     * @type {boolean}
     * @memberof StayOutZones
     */
    'dirty'?: boolean;
    /**
     * List of all stay-out zones for the Automower®.
     * @type {Array<StayOutZone>}
     * @memberof StayOutZones
     */
    'zones'?: Array<StayOutZone>;
}

