/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * System information about a Automower®
 * @export
 * @interface System
 */
export interface System {
    /**
     * The name given to the Automower® by the user when pairing the Automower®
     * @type {string}
     * @memberof System
     */
    'name': string;
    /**
     * The model name of the Automower®
     * @type {string}
     * @memberof System
     */
    'model': string;
    /**
     * The serial number for the Automower®
     * @type {number}
     * @memberof System
     */
    'serialNumber': number;
}

