/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Date and time in seconds from 1970-01-01 in the mower. Time zone is used to format the date and time correctly in the cloud before sending the date and time to the mower. Time zone is only required for some mowers. If your mower supports work areas the time zone will be ignored, since its not is neccassary. The timestamp is used by the mower to trigger the schedule. At the moment you can not get the timestamp from the mower.
 * @export
 * @interface Timer
 */
export interface Timer {
    /**
     * Timestamp in seconds from 1970-01-01. The timestamp needs to be in 24 hours from UTC time.
     * @type {number}
     * @memberof Timer
     */
    'dateTime'?: number;
    /**
     * Time zone needed for mowers that don\'t support work areas. The time zone can be a time zone or GMT +- offset i.e. GMT+2. It\'s recommended to use a time zone to auto adjust for daylight saving time (DST).
     * @type {string}
     * @memberof Timer
     */
    'timeZone'?: string;
}

