/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkAreaAttributes
 */
export interface WorkAreaAttributes {
    /**
     * Duration period in minutes.
     * @type {number}
     * @memberof WorkAreaAttributes
     */
    'duration': number;
    /**
     * Id on the work area
     * @type {number}
     * @memberof WorkAreaAttributes
     */
    'workAreaId': number;
}

