/* tslint:disable */
/* eslint-disable */
/**
 * Automower® Connect API
 * This API allows you to control and obtain information about Automower®.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A work area is part of your lawn that can be scheduled separately and assigned its own cutting height. The schedule and cutting height set for the work area only applies to this area and only when the mower is operating according to the work area schedule. Work areas are created and managed in the Automower® Connect app. In the app you add, edit or delete a work area. You can also name the area, set schedule and cutting height.
 * @export
 * @interface WorkArea
 */
export interface WorkArea {
    /**
     * 
     * @type {number}
     * @memberof WorkArea
     */
    'workAreaId'?: number;
    /**
     * Name of the work area
     * @type {string}
     * @memberof WorkArea
     */
    'name'?: string;
    /**
     * Cutting height in percent. 0-100
     * @type {number}
     * @memberof WorkArea
     */
    'cuttingHeight'?: number;
    /**
     * If the work area is enabled or disabled.
     * @type {boolean}
     * @memberof WorkArea
     */
    'enabled'?: boolean;
    /**
     * The progress on a work are. Only available for EPOS mowers and systematic mowing work areas. See https://www.husqvarna.com/uk/support/husqvarna-self-service/what-is-systematic-mowing-ka-70248/
     * @type {number}
     * @memberof WorkArea
     */
    'progress'?: number;
    /**
     * Timestamp in seconds from 1970-01-01 when the work area was last completed. The timestamp is in local time on the mower. Only available for EPOS mowers and systematic mowing work areas. See https://www.husqvarna.com/uk/support/husqvarna-self-service/what-is-systematic-mowing-ka-70248/
     * @type {number}
     * @memberof WorkArea
     */
    'lastTimeCompleted'?: number;
}

